version: "2"
services:
    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
        expose:
            - 6379
        networks:
            - livechat
    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - 3306:3306
        expose:
            - 27017
        networks:
            - livechat
        environment: #添加环境变量
            MYSQL_ROOT_PASSWORD: 123456
            # MYSQL_USER: root
            # MYSQL_PASSWORD: 123456
    etcd:
        # image: xieyanze/etcd3
        # image: elcolio/etcd
        image: bitnami/etcd:3
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        container_name: etcd
        ports:
            - 2379:2379
        expose:
            - 2380
            - 2379
        networks:
            - livechat
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - 27017:27017
        expose:
            - 27017
        networks:
            - livechat

    chat:
        image: chat:1
        container_name: chat
        ports:
            - 8080:8080
            - 9180:9180
            - 8181:8181
            - 8180:8180
        expose:
            - 8181
        networks:
            - livechat
    voip:
        image: voip:1
        container_name: voip
        ports:
            - 9901:9901
            - 9902:9902
            - 8282:8282
        expose:
            - 8282
        networks:
            - livechat
networks:
    livechat:
        driver: bridge
